export const SOUTH_INDIAN_CITIES = [
  'Ariyalur', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul',
  'Erode', 'Hosur', 'Kanchipuram', 'Karaikudi', 'Karur', 'Krishnagiri',
  'Kumbakonam', 'Madurai', 'Nagapattinam', 'Nagercoil', 'Namakkal', 'Nilgiris',
  'Perambalur', 'Pollachi', 'Pudukkottai', 'Rajapalayam', 'Ramanathapuram',
  'Ranipet', 'Salem', 'Sivakasi', 'Thanjavur', 'Theni', 'Thoothukudi (Tuticorin)',
  'Tiruchirappalli (Trichy)', 'Tirunelveli', 'Tiruppur', 'Tiruvannamalai',
  'Udhagamandalam (Ooty)', 'Vellore', 'Villupuram', 'Virudhunagar',
  'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kochi',
  'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad',
  'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad',
  'Ballari', 'Belagavi', 'Bengaluru', 'Bidar', 'Chikkamagaluru', 'Davanagere',
  'Dharwad', 'Hassan', 'Hubballi', 'Kalaburagi', 'Mandya', 'Mangaluru',
  'Mysuru', 'Raichur', 'Shivamogga', 'Tumakuru', 'Udupi', 'Vijayapura',
  'Anantapur', 'Chittoor', 'Eluru', 'Guntur', 'Kadapa', 'Kakinada',
  'Kurnool', 'Nellore', 'Ongole', 'Rajahmundry', 'Srikakulam', 'Tirupati',
  'Vijayawada', 'Visakhapatnam', 'Vizianagaram',
  'Adilabad', 'Hyderabad', 'Karimnagar', 'Khammam', 'Mahbubnagar', 'Nalgonda',
  'Nizamabad', 'Ramagundam', 'Secunderabad', 'Warangal',
  'Karaikal', 'Mahe', 'Puducherry', 'Yanam',
];